// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineClassroomManagement.Models;

#nullable disable

namespace OnlineClassroomManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowShowResultToStudent")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedByClassMemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("MaxScore")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByClassMemberId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignmentGroupTopicId")
                        .HasColumnType("integer");

                    b.Property<int>("AssignmentInClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentGroupTopicId");

                    b.HasIndex("AssignmentInClassId");

                    b.ToTable("AssignmentGroups");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroupApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("AssignmentGroupTopicId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentGroupId");

                    b.HasIndex("AssignmentGroupTopicId");

                    b.ToTable("AssignmentGroupApprovalRequests");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroupInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("FromMemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("ToMemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentGroupId");

                    b.HasIndex("FromMemberId");

                    b.HasIndex("ToMemberId");

                    b.ToTable("AssignmentGroupInvitations");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentGroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentGroupId");

                    b.HasIndex("MemberId");

                    b.ToTable("AssignmentGroupMembers");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroupTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentInClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("MaxGroupsPerTopic")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("integer");

                    b.Property<int>("MinMembers")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentInClassId");

                    b.ToTable("AssignmentGroupTopics");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentInClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ClassId");

                    b.ToTable("AssignmentInClass");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverColor")
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ClassAppearanceSettings", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowAvatarFrames")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowBadges")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowChatFrames")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ClassId");

                    b.ToTable("ClassAppearanceSettings");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ClassMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrollDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("RoleInClass")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("ClassMembers");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ClassMemberCosmetic", b =>
                {
                    b.Property<int>("ClassMemberId")
                        .HasColumnType("integer");

                    b.Property<int?>("AvatarFrameShopItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("BadgeShopItemId")
                        .HasColumnType("integer");

                    b.Property<int?>("ChatFrameShopItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ClassMemberId");

                    b.HasIndex("AvatarFrameShopItemId");

                    b.HasIndex("BadgeShopItemId");

                    b.HasIndex("ChatFrameShopItemId");

                    b.ToTable("ClassMemberCosmetics");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedByClassMemberId")
                        .HasColumnType("integer");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByClassMemberId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<int>("ParentType")
                        .HasColumnType("integer");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UploadedByClassMemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("PostId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UploadedByClassMemberId");

                    b.ToTable("Documents");

                    b.HasDiscriminator<string>("DocumentType").HasValue("Document");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.DocumentCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("DocumentCollections");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<DateTime>("GradedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GradedByClassMemberId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GradedByClassMemberId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.LiveRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedByClassMemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledEndAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ScheduledStartAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreatedByClassMemberId");

                    b.ToTable("LiveRooms");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LiveRoomId")
                        .HasColumnType("integer");

                    b.Property<int>("SentByParticipantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LiveRoomId");

                    b.HasIndex("SentByParticipantId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkRedirect")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OpenNewTab")
                        .HasColumnType("boolean");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int?>("SenderId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassMemberId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRaisingHand")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LeaveAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LiveRoomId")
                        .HasColumnType("integer");

                    b.Property<string>("LivekitIdentity")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassMemberId");

                    b.HasIndex("LiveRoomId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedByClassMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByClassMemberId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.PostInClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("PostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("PostId");

                    b.ToTable("PostInClass");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.QuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("integer");

                    b.Property<List<int>>("SelectedOptionIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("QuizAnswers");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.QuizOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("QuizOptions");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer");

                    b.Property<double>("Point")
                        .HasColumnType("double precision");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.RewardActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("GrantedByClassMemberId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentType")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("TotalEarnedPoints")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("GrantedByClassMemberId");

                    b.HasIndex("UserId");

                    b.ToTable("RewardActivities");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CostInPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UsageDurationDays")
                        .HasColumnType("integer");

                    b.Property<int>("VisualType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ShopItemInClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("ShopItemInClass");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignmentGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("AssignmentInClassId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int?>("GradeId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubmittedByClassMemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentGroupId")
                        .IsUnique();

                    b.HasIndex("AssignmentInClassId");

                    b.HasIndex("GradeId")
                        .IsUnique();

                    b.HasIndex("SubmittedByClassMemberId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.UserRewardRedemption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRewardRedemptions");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.UserShopItemState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastRedeemedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPurchases")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("UserId", "ClassId", "ShopItemId")
                        .IsUnique();

                    b.ToTable("UserShopItemStates");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.DocumentCollectionItem", b =>
                {
                    b.HasBaseType("OnlineClassroomManagement.Models.Entities.Document");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DocumentCollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("ManualDocumentUrl")
                        .HasColumnType("text");

                    b.Property<string>("ManualFileName")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.HasIndex("DocumentCollectionId");

                    b.HasDiscriminator().HasValue("DocumentCollectionItem");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Assignment", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByClassMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroup", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.AssignmentGroupTopic", null)
                        .WithMany("AssignmentGroups")
                        .HasForeignKey("AssignmentGroupTopicId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.AssignmentInClass", null)
                        .WithMany("AssignmentGroups")
                        .HasForeignKey("AssignmentInClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroupApprovalRequest", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.AssignmentGroup", null)
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("AssignmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.AssignmentGroupTopic", null)
                        .WithMany("ApprovalRequests")
                        .HasForeignKey("AssignmentGroupTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroupInvitation", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.AssignmentGroup", null)
                        .WithMany("GroupInvitations")
                        .HasForeignKey("AssignmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "FromMember")
                        .WithMany()
                        .HasForeignKey("FromMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "ToMember")
                        .WithMany()
                        .HasForeignKey("ToMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromMember");

                    b.Navigation("ToMember");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroupMember", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.AssignmentGroup", null)
                        .WithMany("GroupMembers")
                        .HasForeignKey("AssignmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroupTopic", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.AssignmentInClass", null)
                        .WithMany("AssignmentGroupTopics")
                        .HasForeignKey("AssignmentInClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentInClass", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Class", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ClassAppearanceSettings", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", "Class")
                        .WithOne("AppearanceSettings")
                        .HasForeignKey("OnlineClassroomManagement.Models.Entities.ClassAppearanceSettings", "ClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Class");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ClassMember", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", "Class")
                        .WithMany("Members")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ClassMemberCosmetic", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.ShopItem", "AvatarFrameShopItem")
                        .WithMany()
                        .HasForeignKey("AvatarFrameShopItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ShopItem", "BadgeShopItem")
                        .WithMany()
                        .HasForeignKey("BadgeShopItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ShopItem", "ChatFrameShopItem")
                        .WithMany()
                        .HasForeignKey("ChatFrameShopItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "ClassMember")
                        .WithOne("Cosmetics")
                        .HasForeignKey("OnlineClassroomManagement.Models.Entities.ClassMemberCosmetic", "ClassMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AvatarFrameShopItem");

                    b.Navigation("BadgeShopItem");

                    b.Navigation("ChatFrameShopItem");

                    b.Navigation("ClassMember");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Comment", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByClassMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Document", "Document")
                        .WithOne()
                        .HasForeignKey("OnlineClassroomManagement.Models.Entities.Comment", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Post", null)
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Document");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Document", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Assignment", null)
                        .WithMany("Attachments")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", null)
                        .WithMany("Documents")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Post", null)
                        .WithMany("Documents")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Submission", null)
                        .WithMany("SubmittedFiles")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByClassMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.DocumentCollection", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Grade", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "GradedBy")
                        .WithMany()
                        .HasForeignKey("GradedByClassMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradedBy");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.LiveRoom", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByClassMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Message", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.LiveRoom", "LiveRoom")
                        .WithMany()
                        .HasForeignKey("LiveRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Participant", "SentBy")
                        .WithMany()
                        .HasForeignKey("SentByParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiveRoom");

                    b.Navigation("SentBy");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Notification", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Participant", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "ClassMember")
                        .WithMany()
                        .HasForeignKey("ClassMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.LiveRoom", "LiveRoom")
                        .WithMany()
                        .HasForeignKey("LiveRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassMember");

                    b.Navigation("LiveRoom");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Post", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByClassMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.PostInClass", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.QuizAnswer", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.QuizQuestion", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Submission", null)
                        .WithMany("Answers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.QuizOption", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.QuizQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.QuizQuestion", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Assignment", null)
                        .WithMany("ListQuestions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.RewardActivity", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "GrantedBy")
                        .WithMany()
                        .HasForeignKey("GrantedByClassMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("GrantedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ShopItemInClass", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", null)
                        .WithMany("ShopItemInClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Submission", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.AssignmentGroup", "AssignmentGroup")
                        .WithOne()
                        .HasForeignKey("OnlineClassroomManagement.Models.Entities.Submission", "AssignmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.AssignmentInClass", null)
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentInClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.Grade", "Grade")
                        .WithOne()
                        .HasForeignKey("OnlineClassroomManagement.Models.Entities.Submission", "GradeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ClassMember", "SubmitBy")
                        .WithMany()
                        .HasForeignKey("SubmittedByClassMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignmentGroup");

                    b.Navigation("Grade");

                    b.Navigation("SubmitBy");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.UserRewardRedemption", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("ShopItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.UserShopItemState", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineClassroomManagement.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("ShopItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.DocumentCollectionItem", b =>
                {
                    b.HasOne("OnlineClassroomManagement.Models.Entities.DocumentCollection", null)
                        .WithMany("Documents")
                        .HasForeignKey("DocumentCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Assignment", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ListQuestions");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroup", b =>
                {
                    b.Navigation("ApprovalRequests");

                    b.Navigation("GroupInvitations");

                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentGroupTopic", b =>
                {
                    b.Navigation("ApprovalRequests");

                    b.Navigation("AssignmentGroups");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.AssignmentInClass", b =>
                {
                    b.Navigation("AssignmentGroupTopics");

                    b.Navigation("AssignmentGroups");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Class", b =>
                {
                    b.Navigation("AppearanceSettings");

                    b.Navigation("Documents");

                    b.Navigation("Members");

                    b.Navigation("ShopItemInClasses");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.ClassMember", b =>
                {
                    b.Navigation("Cosmetics");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.DocumentCollection", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.QuizQuestion", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("OnlineClassroomManagement.Models.Entities.Submission", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("SubmittedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
